FROM node:10.16.3-alpine

ADD . /tmp
WORKDIR /tmp

RUN npm install -g serve
RUN npm ci

ARG REACT_APP_INSTRUMENTATION_KEY=instrumentation_key
ARG REACT_APP_API_URL
ARG NODE_ENV
ARG REACT_APP_CORTEXIA_VERSION
ARG REACT_APP_INSTRUMENTATION_KEY
ARG PUBLIC_URL

ENV NODE_ENV=${NODE_ENV}
ENV REACT_APP_API_URL=${REACT_APP_API_URL}
ENV REACT_APP_CORTEXIA_VERSION=${BUILDTIME_CORTEXIA_VERSION}
ENV REACT_APP_INSTRUMENTATION_KEY=${REACT_APP_INSTRUMENTATION_KEY}
ENV PUBLIC_URL=${PUBLIC_URL}

RUN npm run build

ARG ENVIRONMENT=dev
RUN npm run webpack:$ENVIRONMENT

RUN mv /tmp/build /app
WORKDIR /app

ENV REACT_APP_CORTEXIA_VERSION=$BUILDTIME_CORTEXIA_VERSION

EXPOSE 5000

CMD serve -s .
