# this container is made for conveniency to ease developement process
# the resulting image should not be pushed to any repository
# since it wraps all files in the root directory of the project

FROM node:19-alpine

ADD . /app

WORKDIR /app
VOLUME ["/app/src"]

RUN npm config set legacy-peer-deps true
RUN npm ci

ARG BUILDTIME_CORTEXIA_VERSION=0.0.0
ENV REACT_APP_CORTEXIA_VERSION=$BUILDTIME_CORTEXIA_VERSION

EXPOSE 3000

CMD npm run react-start
